[build-system]
requires = [
    "setuptools"
]
build-backend = "setuptools.build_meta"

[project]
name = "spagrn"
version = "1.0.7"
authors = [
    {name = "Yao LI, Lidong GUO, Mengyang XU", email = "liyao1@genomics.cn, guolidong@genomics.cn, xumengyang@genomics.cn"},
]
description = "A comprehensive tool to infer TF-centred, spatial gene regulatory networks for the spatially resolved transcriptomic data."

[tool.setuptools]
packages = ["spagrn"]
