[build-system]
requires = [
    "setuptools", "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "spagrn"
version = "1.0.7"
authors = [
    {name = "Yao LI, Lidong GUO, Mengyang XU", email = "liyao1@genomics.cn, guolidong@genomics.cn, xumengyang@genomics.cn"},
]
description = "A comprehensive tool to infer TF-centred, spatial gene regulatory networks for the spatially resolved transcriptomic data."
readme = READ.me
requires-python = ">=3.7,<3.11"
license = "GPL-3.0+"
classifiers=[
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
	"Operating System :: OS Independent",
]
dependencies = [
	"anndata==0.8.0", 
	"pandas<2.0.0,>=1.3.4", 
	"scanpy==1.9.1", 
	"seaborn", 
	"matplotlib", 
	"pyscenic==0.12.1", 
	"hotspotsc==1.1.1", 
	"scipy", 
	"numpy", 
	"dask", 
	"arboreto", 
	"ctxcore>=0.2.0", 
	"scikit-learn"
]

[tool.setuptools]
packages = ["spagrn"]
